# Generated by Django 4.2.1 on 2023-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='dvg_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
