# Generated by Django 4.2.1 on 2023-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_subscriber_dvg_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber'},
        ),
    ]
